### ISSUE TITLE
Add AsyncSemaphore data structure

### ISSUE THREAD

**Issue by Supereg** [StanfordSpezi/SpeziFoundation#5]
### Problem

In some cases, it is very useful to ensure exclusive access in an asynchronous context (e.g., ensure that an async method within an actor is only entered by a single called at a time).
SpeziBluetooth introduced a `AsyncSemaphore` data structure within the latest release, see [here](https://github.com/StanfordSpezi/SpeziBluetooth/blob/133c8331b4af2742c814d65cc3e1b832b82d030c/Sources/SpeziBluetooth/Utils/AsyncSempahore.swift).

### Solution

This data structure would be great to reuse across the Spezi framework ecosystem (e.g., there is currently also a need in https://github.com/StanfordSpezi/SpeziLLM/pull/45).
This would require to move out the data structure from SpeziBluetooth, add documentation and dedicated unit testing for within SpeziFoundation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by philippzagar** [comment]
AsyncSemaphore has been added to SpeziFoundation in: https://github.com/StanfordSpezi/SpeziFoundation/pull/7

**Comment by PSchmiedmayer** [comment]
Thank you @philippzagar!
